version: '3'
services:
  frontend:
    privileged: true
    tty: true
    stdin_open: true
    build:
      context: ./react_ts_app
      dockerfile: Dockerfile.dev
    image: tar-dev-front
    container_name: tar-dev-front
    environment:
      - NODE_ENV=development
    volumes:
      - ./react_ts_app:/usr/src/app
    networks:
      - app_net_dev
    ports:
      - "3000:3000"
    command: /bin/sh
  backend:
    tty: true
    stdin_open: true
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    image: tar-dev-api
    container_name: tar-dev-api
    platform: linux/x86_64
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./api/app:/app/
    networks:
      - app_net_dev
    ports:
      - "8000:8000"
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: tar-dev-db
    container_name: tar-dev-db
    platform: linux/x86_64
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 1s
      retries: 10
      start_period: 3s
      timeout: 20s
    volumes:
      - ./mysql/db:/var/lib/mysql
    expose:
      - 3306
    env_file:
      - ./mysql/db.env
    networks:
      - app_net_dev
    
networks:
  app_net_dev:
    driver: bridge
